config/routes.rb
Rails.application.routes.draw do
  resources :visitors do
    collection do
      get 'import'
      get 'search'
      get 'graph_filter'
    end
  end

  root 'home#index'
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  require 'csv'
  #Using Enum for event type
  enum event_type: {entry: 0, exit: 1}

  #Apply Validations
  validates_presence_of :ticked_id, :event_type, :event_time
  validates_numericality_of :ticked_id, :event_time
  validates_inclusion_of :event_type, in: Visitor.event_types.keys, :message => "is incorrect, only exit and entry is acceptable"

  #Import Data
  def self.import(file)
    processed_data = {}
    current = 0
    visitors_count = 0
    CSV.foreach(file, headers: true) do |row|
      visitor_hash = row.to_hash
      type_of_event = visitor_hash['event_type'].to_sym
      #Check if event already happened
      visitor = Visitor.where(ticked_id: visitor_hash['ticked_id'], event_type: Visitor.event_types[type_of_event])
      #Persist data into DB
      self.persist_imported_data(visitor_hash, visitor)
      #Pre process data for searching
      if visitor_hash['event_type'] == "entry"
        visitors_count += 1
        self.increment(processed_data, visitor_hash, current, visitors_count)
      else
        self.decrement(processed_data, visitor_hash, current, visitors_count)
      end
      #Update current
      current = processed_data[visitor_hash['event_time']].first[:current_visitors]
    end
    PreProcessedDatum.process_data(processed_data)
  end

  private

  def self.persist_imported_data(visitor_hash, visitor)
    if visitor.count >= 1
      p 'visitor already exits, updating data'
      visitor.first.update_attributes(visitor_hash)
    else
      Visitor.create!(visitor_hash)
    end
  end

  def self.increment(processed_data, visitor_hash, current, visitors_count)
    processed_data[visitor_hash['event_time']] = event_specific_data(processed_data[visitor_hash['event_time']], current+1, visitors_count, 1, 0)
  end

  def self.decrement(processed_data, visitor_hash, current, visitors_count)
    processed_data[visitor_hash['event_time']] = event_specific_data(processed_data[visitor_hash['event_time']], current-1, visitors_count, 0, 1)
  end

  def self.event_specific_data(time_specific_data, current, visitors_count, entry, exit)
    event_based_data = []
    event_based_data_hash = {}
    event_based_data_hash[:current_visitors] = current
    event_based_data_hash[:total_visitors] = visitors_count

    #Check if value already exist
    if time_specific_data
      event_based_data_hash[:entry] = time_specific_data.first[:entry]+ entry
      event_based_data_hash[:exit] = time_specific_data.first[:exit]+ exit
    else
      event_based_data_hash[:entry] = entry
      event_based_data_hash[:exit] = exit
    end

    event_based_data << event_based_data_hash
    p event_based_data
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: [:show, :edit, :update, :destroy]

  # GET /visitors
  # GET /visitors.json
  def index
    @visitors = Visitor.all
  end

  # GET /visitors/1
  # GET /visitors/1.json
  def show
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors
  # POST /visitors.json
  def create
    @visitor = Visitor.new(visitor_params)

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to @visitor, notice: 'Visitor was successfully created.' }
        format.json { render :show, status: :created, location: @visitor }
      else
        format.html { render :new }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1
  # PATCH/PUT /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to @visitor, notice: 'Visitor was successfully updated.' }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.json
  def destroy
    @visitor.destroy
    respond_to do |format|
      format.html { redirect_to visitors_url, notice: 'Visitor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    #TODO: Remove the hardcoded file name
    file_path = Rails.public_path.join('visitors.csv')
    begin
      logger.info("Importing file: #{file_path}")
      @visitors = Visitor.import(file_path)
      logger.info("File imported : #{@visitors}")
      respond_to do |format|
        format.html { redirect_to visitors_url, notice: 'Imported successfully.' }
        format.json { render :index, status: :ok, location: @visitors }
      end
    rescue Exception => e
      logger.error("There was an error in importing data  #{e}")
      render json: e.message, status: :unprocessable_entity #Returining only in json
      #redirect_to root_url, alert: "Invalid CSV file format."
    end
  end

  def search
    @visitors = 0
    searched_time = params[:time]
    searched_time = parse_datetime_params(searched_time, "event_time")
    logger.info searched_time
    #Change date time to timestamp
    searched_timestamp = searched_time.to_i
    logger.info "*******************************Searched Time**********************************************"
    logger.info("Searched time is:  #{searched_time} and Timestamp is #{searched_timestamp}")
    searched_date = Time.at(searched_timestamp).strftime("%Y-%m-%d")
    result = PreProcessedDatum.where("event_time <= ? AND date(from_unixtime(event_time)) = ?", searched_timestamp, searched_date).order('event_time DESC').limit(1)
    logger.info("*******************************Got The Query Response**********************************************")
    logger.info(result)
    @visitor = result.first

    respond_to do |format|
      format.html { render :search, notice: 'Visitor was successfully created.' }
      format.json { render :search, status: :created, location: @visitor }
      format.js
    end
  end

  def graph_filter
    @visitors = PreProcessedDatum.all
    respond_to do |format|
      format.html { render :search, notice: 'Visitor was successfully created.' }
      format.json { render :search, status: :created, location: @visitor }
      format.js
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_visitor
    @visitor = Visitor.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def visitor_params
    params.require(:visitor).permit(:event_type, :event_time)
  end
end

app/helpers/visitors_helper.rb
module VisitorsHelper
  def format_visitors_graph_data(visitors)
    #We can also pass this date for old dates
    #today = Time.now.strftime("%Y-%m-%d")
    data = []
    visitors.each do |visitor|
      temp_hash = {}
      temp_hash[:total] = visitor.till_now
      temp_hash[:entry] = visitor.entry
      temp_hash[:exit] = visitor.exit
      temp_hash[:event_time] = Time.at(visitor.event_time).strftime("%d-%m-%Y %H:%M:%S")
      data << temp_hash
    end
    data
  end

  def temp
    data = []
    temp_hash = {}
    temp_hash[:total] = 0
    temp_hash[:entry] = 0
    temp_hash[:exit] = 0
    temp_hash[:event_time] = Time.now.strftime("%d-%m-%Y %H:%M:%S")
    data << temp_hash
  end
end

app/views/visitors/_form.html.erb
<%= form_for(@visitor) do |f| %>
  <% if @visitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visitor.errors.count, "error") %> prohibited this visitor from being saved:</h2>

      <ul>
      <% @visitor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ticked_id %><br>
    <%= f.text_field :ticked_id %>
  </div>
  <div class="field">
    <%= f.label :event_type %><br>
    <%= f.text_field :event_type %>
  </div>
  <div class="field">
    <%= f.label :event_time %><br>
    <%= f.text_field :event_time %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visitors/_visitors.html.erb
<h2>
    Number of visitors at searched time is: <%= @visitor ? @visitor.till_now : 0 %>
</h2>

app/views/visitors/_visitors_graph.html.erb
<%= content_tag :div, "", id: "visitors_graph", data: {visitos: format_visitors_graph_data(@visitors) } %>

app/views/visitors/edit.html.erb
<h1>Editing Visitor</h1>

<%= render 'form' %>

<%= link_to 'Show', @visitor %> |
<%= link_to 'Back', visitors_path %>

app/views/visitors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Visitors</h1>

<table>
  <thead>
    <tr>
      <th>Ticked</th>
      <th>Event type</th>
      <th>event_time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visitors.each do |visitor| %>
      <tr>
        <td><%= visitor.ticked_id %></td>
        <td><%= visitor.event_type %></td>
        <td><%= visitor.event_time %></td>
        <td><%= link_to 'Show', visitor %></td>
        <td><%= link_to 'Edit', edit_visitor_path(visitor) %></td>
        <td><%= link_to 'Destroy', visitor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visitor', new_visitor_path %>

app/views/visitors/new.html.erb
<h1>New Visitor</h1>

<%= render 'form' %>

<%= link_to 'Back', visitors_path %>

app/views/visitors/search.html.erb
<%= @visitors %>

app/views/visitors/search.js.erb
$("#result_data").html("<%= escape_javascript(render partial: 'visitors', locals: { items: @visitors } ) %>");

app/views/visitors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticked:</strong>
  <%= @visitor.ticked_id %>
</p>

<p>
  <strong>Event Type:</strong>
  <%= @visitor.event_type %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @visitor.event_time %>
</p>

<%= link_to 'Edit', edit_visitor_path(@visitor) %> |
<%= link_to 'Back', visitors_path %>