config/routes.rb
Rails.application.routes.draw do
  resources :visitors do
    collection do
      get 'import'
      get 'search'
      get 'graph_filter'
    end
  end

  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #TODO: Add filters, don't use all
    @visitors = PreProcessedDatum.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>
    Task One :
</h1>
<div class="row">
    <div class="col-md-12">
        <%= form_tag(search_visitors_url, method: :get, :remote => true) do %>
            <div class="form-group">
                <div class="input-group">
                    <%= datetime_select("time", "event_time", prompt: {second: 'Select second', minute: 'Select minute', hour: 'Select hour', day: 'Select day', month: 'Select month', year: 'Select year'}, start_year: 2000, end_year: Time.now.year, :include_seconds => true, :class => 'form-control') %>
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
                        <i class="glyphicon glyphicon-search"></i> Search
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div id="result_data">
        </div>
    </div>
</div>


<h1>
    Task Two :
</h1>

<i>TODO: add filters </i>
<div id="graph_data">
    <%= content_tag :div, "", id: "visitors_graph", data: {visitos: format_visitors_graph_data(@visitors)} %>
</div>